// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  benefit: dynamic(() => import("./Benefit")),
  contact_form: dynamic(() => import("./ContactForm")),
  feature: dynamic(() => import("./Feature")),
  footer: dynamic(() => import("./Footer")),
  hero: dynamic(() => import("./Hero")),
  image: dynamic(() => import("./Image")),
  ingredient: dynamic(() => import("./Ingredient")),
  product: dynamic(() => import("./Product")),
  quote: dynamic(() => import("./Quote")),
  separator: dynamic(() => import("./Separator")),
  testimonials: dynamic(() => import("./Testimonials")),
  text: dynamic(() => import("./Text")),
};
